### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rushikeshadhav**
Steps to setup locally
How to raise a PR added

### CODE REVIEW

**Comment by NegiAkash890** [comment]
> Steps to setup locally How to raise a PR added
Hi @rushikeshadhav . I have some suggestions if you like to work on that. Recently, I added linter and prettier to the project. Can you also add some information regarding that too. If you can please do and if you can't no worries I will do it myself ;)

**Comment by rushikeshadhav** [comment]
#19

**Comment by NegiAkash890** [comment]
> Added contributors section to readme Kindly review this #19 If any changes let me know

Please read  [this](https://github.com/NegiAkash890/editor-frontend/pull/18#issuecomment-986169234) comment

**Comment by rushikeshadhav** [comment]
Hey @NegiAkash890 actually I don't have knowledge of linter. I know prettier which is a vs code extension, I can add information about prittier.

**Pull request merged**
