### PR TITLE
Added boilerplate code using context

### PR DESCRIPTION
**Pull request by developer-diganta**
Adding Boilerplate Code (#4 )
Added boiler plate code for each language
image

image

image

### CODE REVIEW

**Comment by developer-diganta** [comment]
@NegiAkash890  Please review my PR.

**Comment by NegiAkash890** [comment]
> @NegiAkash890 Please review my PR.

Hi @developer-diganta  good work but since we have two PRs using redux. I am actually thinking whether we can combine the redux together somehow. Tagging PR #8  . Let me know your view on same?

**Comment by NegiAkash890** [comment]
Hi @developer-diganta I believe that redux for small changes isn't necessary. We can do something like what you have done in the file ``` src/reducers/language.js ``` and then handling it in app accordingly, What do you think ?

**Comment by developer-diganta** [comment]
@NegiAkash890  Sorry I had some college work... Can I try it with context api?

**Comment by NegiAkash890** [comment]
> @NegiAkash890 Sorry I had some college work... Can I try it with context api?

No worries! Yes, you can for sure. If you face any issue you can ask here.

**Comment by developer-diganta** [comment]
@NegiAkash890  I have used context...Can you please check if everything is working fine?

**Comment by NegiAkash890** [comment]
> @NegiAkash890 I have used context...Can you please check if everything is working fine?

Ok I will start the review soon!

**Comment by NegiAkash890** [comment]
> @NegiAkash890 I have used context...Can you please check if everything is working fine?

Hi, @developer-diganta are you using the same linter configuration as projects?

**Comment by developer-diganta** [comment]
@NegiAkash890  Hello! I am not sure but I do not think it is different. Could you please tell me how to check it?

**Comment by NegiAkash890** [comment]
> @NegiAkash890 Hello! I am not sure but I do not think it is different. Could you please tell me how to check it?

No worries regarding that. Everything is working fine. There is one more thing that needs to be done can you move context from App to index file.

**Comment by developer-diganta** [comment]
@NegiAkash890 I tried doing it but there is one problem . For the context, I need to send a lang variable with a function to update it (useState) but for index how will I define useState? (since it is outside function component)

**Comment by NegiAkash890** [comment]
Just like we have theme context provided we can have same for  this one too.

**Comment by NegiAkash890** [comment]
Thanks, @developer-diganta for your contribution so far, @arp99 went ahead and implemented this functionality.

**Pull request closed without merging**
