### PR TITLE
Feature Upload File Added

### PR DESCRIPTION
**Pull request by shreya024**
Resolved issue #21 

With this new File Upload feature, the user can upload a file and the code inside the file will be transferred to the IDE where he/she can then edit or run the program.

### CODE REVIEW

**Comment by shreya024** [comment]
@NegiAkash890 Kindly review my PR

**Comment by NegiAkash890** [comment]
> @NegiAkash890 Kindly review my PR

Ok Shreya I will start the review soon !

**Comment by NegiAkash890** [comment]
Hi, Shreya can you fix this:
localhost_3000_

The upload should not go out of the viewport and should span full width.

**Comment by shreya024** [comment]
> Hi, Shreya can you fix this:
> 
> localhost_3000_
> 
> The upload should not go out of the viewport and should span full width.

I will try my best.It is okay if I make it look like the Editor tab?

**Comment by shreya024** [comment]
I have made the changes.Kindly check now

**Comment by NegiAkash890** [comment]
> I have made the changes. Kindly check now

Hi, Shreya nice work so far. I was thinking instead of having an upload button at the bottom can we have a small button in editor tab next to copy to the clipboard icon.

**Comment by shreya024** [comment]
> > I have made the changes. Kindly check now
> 
> Hi, Shreya nice work so far. I was thinking instead of having an upload button at the bottom can we have a small button in editor tab next to copy to the clipboard icon.

Yes I can do that.But I would be adding a download button for my next PR there.
And if we just do a small upload button then we can't show the name of the uploaded file.
So, I thought it would look better below the editor.

However,if you still prefer the top postion ,let me know I will do it :)

**Comment by shreya024** [comment]
@NegiAkash890 Kindly reply and let me know regarding the position of upload file component.

**Comment by NegiAkash890** [comment]
Sorry for the delay we can have a small upload button to the left of the play button.

**Comment by shreya024** [comment]
> Sorry for the delay we can have a small upload button to the left of the play button.

Okay, I have made the changes, @NegiAkash890 Kindly review now.

**Comment by shreya024** [comment]
Thank you for merging. @NegiAkash890 Kindly add the SWOC labels :)

**Comment by shreya024** [comment]
@NegiAkash890 Kindly add this the SWOC scoresheet...my PID is 921

**Comment by NegiAkash890** [comment]
Updated

**Pull request merged**
